const Assets = {
  ic_filter: require('../assets/ic_filter.png'),
  ic_notification: require('../assets/ic_notification.png'),
  ic_search: require('../assets/ic_search.png'),
  img_banner: require('../assets/img_banner.png'),
  img_healthhy: require('../assets/img_healthhy.png'),
  img_vegan: require('../assets/img_vegan.png'),
  Pattern: require('../assets/Pattern.png'),
  intro: require('../assets/intro.png'),
  Illustration: require('../assets/Illustration.png'),
  Logo: require('../assets/Logo.png'),
  facebook: require('../assets/facebook.png'),
  google: require('../assets/google.png'),
  check: require('../assets/check.png'),
  show: require('../assets/show.png'),
  lock: require('../assets/lock.png'),
  back: require('../assets/back.png'),
  visa: require('../assets/visa.png'),
  paypal: require('../assets/paypal.png'),
  payoneer: require('../assets/payoneer.png'),
  gallery: require('../assets/gallery.png'),
  camera: require('../assets/camera.png'),
  close: require('../assets/close.png'),
  Photo: require('../assets/Photo.png'),
  pin: require('../assets/pin.png'),
  congra: require('../assets/congra.png'),
  Email: require('../assets/Email.png'),
  Message: require('../assets/Message.png'),
  profilephoto: require('../assets/profilephoto.png'),
  profilephoto1: require('../assets/profilephoto1.png'),
  profilephoto2: require('../assets/profilephoto2.png'),
  avatar: require('../assets/avatar.png'),
  edit: require('../assets/edit.png'),
  voucher: require('../assets/voucher.png'),
  spacy: require('../assets/spacy.png'),
};

export default Assets;
